In [6]:
import os
import numpy as np
import pandas as pd
%pip install scipy
from scipy.stats import chisquare

Requirement already satisfied: scipy in ./.greenSD_venv/lib/python3.12/site-packages (1.17.0)
Requirement already satisfied: numpy<2.7,>=1.26.4 in ./.greenSD_venv/lib/python3.12/site-packages (from scipy) (2.3.2)
Note: you may need to restart the kernel to use updated packages.

In [10]:
no_corr_beginner_not_correct = 35
no_corr_beginner_correct = 19
no_corr_expert_not_correct = 14+1
no_corr_expert_correct = 7


#       No correlation            'Correct'                  'Not correct'  
data = [
    ['Beginner', 'No correlation', no_corr_beginner_correct, no_corr_beginner_not_correct],
    ['Expert', 'No correlation',   no_corr_expert_correct,   no_corr_expert_not_correct],
]

df = pd.DataFrame(data, columns=['Experience', 'Correlation Type', 'Correct', 'Not correct'])
df

  Experience Correlation Type  Correct  Not correct
0   Beginner   No correlation       19           35
1     Expert   No correlation        7           15

In [ ]:
df_long = df.melt(
    id_vars=['Experience', 'Correlation Type'],
    value_vars=['Correct', 'Not correct'],
    var_name='Proxy identified',
    value_name='Observed'
)

df_long['Expected'] = df_long.groupby(['Experience'])['Observed'].transform('sum') * df_long.groupby('Proxy identified')['Observed'].transform('sum') / df_long['Observed'].sum()
df_long['Chi-Square'] = (df_long['Observed'] - df_long['Expected']) ** 2 / df_long['Expected']
df_long['p-value'] = df_long.apply(lambda row: chisquare([row['Observed'], row['Expected']])[1], axis=1)

df_long

,Experience,Correlation Type,Proxy identified,Observed,Expected,Chi-Square,p-value
0,Beginner,No correlation,Correct,19,19.0,0.0,1.0
1,Expert,No correlation,Correct,7,7.0,0.0,1.0
2,Beginner,No correlation,Not correct,35,35.0,0.0,1.0
3,Expert,No correlation,Not correct,15,15.0,0.0,1.0

In [ ]:
scenario_data = {
    "No correlation": {1: 0, 2: 0, 3: 19, 4: 35, 5: 0},
    "No correlation (R)":       {1: 0, 2: 0, 3: 7, 4: 14, 5: 1},

    "Negative correlation": {1: 1, 2: 12, 3: 14, 4: 22, 5: 10},
    "Negative correlation (R)":       {1: 2, 2: 6, 3: 6, 4: 10, 5: 2},

    "Moderate positive correlation": {1: 0, 2: 2, 3: 5, 4: 37, 5: 12},
    "Moderate positive correlation (R)":       {1: 0, 2: 0, 3: 3, 4: 17, 5: 7},

    "Strong positive correlation": {1: 0, 2: 2, 3: 6, 4: 47, 5: 29},
    "Strong positive correlation (R)":       {1: 0, 2: 0, 3: 1, 4: 16, 5: 10}, 
}